services:
#    wd_platform.example:
#        class: WD\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    wd_platform.antispam:
        class: WD\PlatformBundle\Antispam\WDAntispam
        arguments: [@mailer, %locale%, 50]